### ISSUE TITLE
Performance test | Mirai seriously outperforms Suki

### ISSUE THREAD

**Issue by REALMWTH** [SuCraft/Suki#6]
Miral timings: https://timin.gs/?id=283d611ae22d48c79ecbb6b23e1d243e

Suki timings:  https://timin.gs/?id=88ed0483bf094ffe9bb96164d484775b

**Comment by MartijnMuijsers** [comment]
Thank you for testing!

Could you upload the `suki-global.yml` and `suki-world-defaults.yml`? I have not added them to Timings yet.

**Comment by REALMWTH** [comment]
global

```
# This is the global configuration file for Suki.
# As you can see, there's a lot to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to Suki,
# join us in our Discord for SuCraft, or check the GitHub Wiki pages.
# 
# The world configuration options are inside
# their respective world folder. The files are named suki-world.yml
# 
# Wiki: https://github.com/SuCraft/Suki/wiki
# Discord: https://discord.com/invite/pbsPkpUjG4

_version: 17
console-logs:
  change-invalid-pool-element-level-to-info: true
  chat-messages:
    empty: false
    not-secure: false
  invalid-client-view-distance: true
  invalid-statistics: false
  login-protocol:
    packets:
      handshake: false
      login-start: false
      set-compression: false
  move-checks:
    too-quickly:
      self: true
      vehicle: true
    wrongly:
      self: true
      vehicle: true
enchantability:
  bane-of-arthropods:
    hoe: false
    pickaxe: false
    shovel: false
  efficiency:
    sword: false
  fire-aspect:
    axe: false
    hoe: false
    pickaxe: false
    shovel: false
  fortune:
    sword: false
  knockback:
    axe: false
    hoe: false
    pickaxe: false
    shovel: false
  looting:
    axe: false
    bow: false
    crossbow: false
    hoe: false
    pickaxe: false
    shovel: false
    trident: false
  protection:
    elytra: false
  sharpness:
    hoe: false
    pickaxe: false
    shovel: false
  silk-touch:
    sword: false
  smite:
    hoe: false
    pickaxe: false
    shovel: false
  thorns:
    elytra: false
hide-game-modes:
  replacement: survival
keepalive:
  kick-player-for:
    late-response: false
    unexpected-response: false
    wrong-response-id: false
  send-interval: 3000
login-protocol:
  slow-login-timeout: 600
network-constrained-chunk-sending:
  assume-packets-in-transit-arrived-after-time: 600
  ignore-network-conditions-for-chunks-within-chessboard-distance: 1
plugins:
  hide-if-no-permission: true
  show-legacy-asterisk: false
signed-chat:
  enabled: false
  if-disabled:
    hide-insecure-popup: true
    use-chat-preview: false
survival-debug-stick:
  switch-property-timeout: 300
tps-catchup:
  max: 50
view-distance:
  allow-invalid-client-view-distance: false
  see:
    max-total-chunks: 100000
  track:
    max-total-chunks: 100000

```

**Comment by REALMWTH** [comment]
world-defaults

```
# This is the world defaults configuration file for Suki.
# As you can see, there's a lot to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to Suki,
# join us in our Discord for SuCraft, or check the GitHub Wiki pages.
# 
# Configuration options here apply to all worlds, unless you specify overrides inside
# the world-specific config file inside each world folder.
# 
# Wiki: https://github.com/SuCraft/Suki/wiki
# Discord: https://discord.com/invite/pbsPkpUjG4

_version: 19
bone-meal-regrows-bark:
  bone-meal-is-used-up-chance: 1.0
  enabled: false
break-blocks-in-survival:
  barrier-if-holding-barrier: false
  light-if-holding-light: false
difficulty-changes:
  cave-spiders-have-poison-on-easy-difficulty: false
  lightning-spawns-fire: true
  minimum-health-after-starving: -1.0
  players-share-villager-gossips:
    positive:
      always: false
  raids-are-always-hard: false
  spiders-with-effects-on-all-difficulties: false
  villager-reputation-changes:
    cured:
      major-positive: 20
      minor-positive: 25
    trade:
      trading: 2
    villager-hurt:
      major-negative: 0
      minor-negative: 25
    villager-killed:
      major-negative: 25
      minor-negative: 0
  wither-effect-from-wither-skulls-on-easy-difficulty: false
  zombie-reinforcements-on-all-difficulties: false
entity-ticking:
  immune-from-inactive:
    non-sitting-pets: true
    sheared-sheep: true
    ticks:
      baby: 5
      mob-targeting-mob:
        axolotl-targeting-fish: 0
        axolotl-targeting-squid: 0
        cat-targeting-rabbit: 0
        default: 0
        enderman-targeting-endermite: 0
        fox-targeting-chicken: 0
        guardian-targeting-squid: 0
        llama-targeting-wolf: 0
        mob-targeting-turtle: 0
        ocelot-targeting-chicken: 0
        piglin-targeting-hoglin: 0
        piglin-targeting-wither-skeleton: 0
        polar-bear-targeting-fox: 0
        snow-golem-targeting-non-player: 0
        witch-targeting-witch: 0
        wither-skeleton-targeting-iron-golem: 0
        wither-skeleton-targeting-piglin: 0
        wither-skeleton-targeting-snow-golem: 0
        wolf-targeting-fox: 0
        wolf-targeting-sheep: 0
        zoglin-targeting-non-player: 0
  skipped-active-entity-ratio:
    ratio: 0.75
  wake-up-duration-standard-deviation-ratio: 0.2
interaction-distance:
  max: 6.0
item-pickup:
  hopper:
    minecart-immunity:
      detection:
        horizontal-distance: 32.0
        max-age: 1200
        tick-rate: 20
        vertical-distance: 4.0
        while-inactive: true
      duration: 200
    tick-rate: 1
  villager:
    delay-after-drop: 100
lootables:
  only-refresh-for-players: true
mob-spawning:
  all-nether-bricks-count-as-fortress: false
move-checks:
  too-quickly:
    self: true
    vehicle: true
  wrongly:
    self: true
    vehicle: true
network-constrained-chunk-sending:
  max-chunk-packets-in-transit:
    target-player-chunk-send-rate-margin-factor: 1.15
never-despawn-entities-due-to-distance:
  wither: false
prevent-block-update-client-lag:
  enabled: false
relocate-corrupted-chunks:
  enabled: true
view-distance:
  if-can-see-but-not-tracking:
    send-chunk-refresh: false
    send-end-portal-fill-sound: true
    send-ender-dragon-spawn-sound: true
    send-wither-spawn-sound: true
  load:
    limit-by-client-view-distance: true
    limit-by-see-view-distance: true
    max: -1
    per-player: true
  see:
    limit-by-client-view-distance: true
    max: -1
    per-player: true
  track:
    limit-by-client-view-distance: true
    max: 10
    per-player: true

```

**Comment by REALMWTH** [comment]
Forgot to mention, that all bots and me are using `view-distance 10`

**Comment by MartijnMuijsers** [comment]
The client bots are using view distance 10?

**Comment by MartijnMuijsers** [comment]
(Suki does *not* have the Paper chunk rewrite yet, but the latest version of Mirai *does*)

**Comment by MartijnMuijsers** [comment]
How much RAM do you have?

**Comment by REALMWTH** [comment]
Fixed, gonna have another stress test run

I have 32gb of RAM

**Comment by MartijnMuijsers** [comment]
And what is your `simulation-distance`?

**Comment by REALMWTH** [comment]
`simulation-distance: 4`

**Comment by MartijnMuijsers** [comment]
Your settings
```
  see:
    max-total-chunks: 100000
  track:
    max-total-chunks: 100000
```

`see` should be based on RAM. I think for your RAM, `50000` would be better, but maybe `100000` is okay, hard to say.
`track` should be based on CPU. I think for your CPU, somewhere between `15000` and `30000` would be better.
